### ISSUE TITLE
Remove placeholder video uploading

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#101]
Now that https://github.com/hackclub/summer-scrapbook/pull/91 is live, we can reduce storage use on Airtable by removing the placeholder video uploading alongside Mux.

**Comment by MatthewStanciu** [comment]
![IMG_0438](https://user-images.githubusercontent.com/14811170/91743205-7687a400-eb85-11ea-859c-a30fa0c7d56a.png)
