### ISSUE TITLE
Add “@scrappy retry”

### ISSUE THREAD

**Issue by MatthewStanciu** [hackclub/scrappy#115]
Some posts just don’t work for some reason and I have no idea why. You should be able to type “@scrappy retry” in the thread and it’ll try again

**Comment by sampoder** [comment]
I think this is large videos mostly

**Comment by MatthewStanciu** [comment]
It happens for some large videos but it's also happened for seemingly no reason to Jess and Claire many times, and I can't figure out why. Also sometimes the server goes down or something and it just doesn't work

**Comment by sampoder** [comment]
if we merge and the pr is correct #128 then I feel this will be easy to implement, one ish line of code

**Comment by sampoder** [comment]
This has been done a while back now! React with `scrappy-retry` to trigger it
