### ISSUE TITLE
Scrappy Mending CSS in an Interesting Manner 

### ISSUE THREAD

**Issue by sampoder** [hackclub/scrappy#143]
<img width="823" alt="Screenshot 2021-01-07 at 9 23 10 PM" src="https://user-images.githubusercontent.com/39828164/103897449-8e23fa00-512e-11eb-9bd5-d72972b1f116.png">

View above, was "fixed" in https://github.com/hackclub/scrappy/commit/9829b1bcc494c88fa9f2e6ab85629d1396bf186e but I feel like this breaks something @MatthewStanciu thoughts?

**Comment by MatthewStanciu** [comment]
@sampoder did https://github.com/hackclub/scrappy/commit/9829b1bcc494c88fa9f2e6ab85629d1396bf186e end up breaking something? if not i think we can close this

**Comment by sampoder** [comment]
not that I'm aware of, I think we're good to close the issue
