### ISSUE TITLE
Transform user mentions

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#15]
![9DE7CBE0-9817-4C8C-B9D9-01CDE51544F3](https://user-images.githubusercontent.com/5074763/85216227-f60c2200-b34f-11ea-9ce9-eb10891b3398.jpeg)

Would be nice to switch these to @-mentions so we could easily autolink them on the frontend.

**Comment by sampoder** [comment]
oooh and emoji

**Comment by lachlanjc** [comment]
Yeah I was going to implement on the frontend but actually it’d be way more performant to do backend-side

**Comment by sampoder** [comment]
`export const formatText = (text) => {
  //<@USLACKBOT>
  // if (text.includes('<@')) {
  //   const userId = text.split('@').pop().split('>')[0]
  //   console.log(`userId`, userId)
  //   const userProfile = await fetch(`https://slack.com/api/users.profile.get?token=${process.env.SLACK_BOT_TOKEN}&user=${userId}`)
  // }
  let userIds = text.split(' ').filter((word) => word.includes('<@U'))
  if (userIds.length == 0) return text

  userIds.forEach(async (userId) => {
    try {
      const id = userId.split('@').pop().split('>')[0]
      const userProfile = await fetch(
        `https://slack.com/api/users.profile.get?token=${process.env.SLACK_BOT_TOKEN}&user=${id}`
      ).then((r) => r.json())
      console.log(userProfile)
      const displayName = userProfile.profile.display_name
      userId = `@${displayName}`
    } catch (err) {
      console.log(err)
    }
  })
  console.log(userIds.join(' '))
  return userIds.join(' ')
}`

**Comment by lachlanjc** [comment]
You’re an icon, thank you so much! @MatthewStanciu will test out/implement today.

**Comment by sampoder** [comment]
oh lol i didnt write this code, i found it in pre existing code in this repo

**Comment by MatthewStanciu** [comment]
Yep this is my code that I wrote in the beginning stages of scrappy but never finished. It doesn’t work, but it’s pretty close. If anyone wants to help get it all the way there, it would be super appreciated :)

**Comment by sampoder** [comment]
Try to do this, Javascript is confusing

#26 makes it a bit cleaner
