### ISSUE TITLE
Scrappy reacts with beachball to URLs in thread messages

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#17]

**Comment by thatrobotdev** [comment]
This has happened with https://hackclub.slack.com/archives/C01504DCLVD/p1593149830283200?thread_ts=1593149611.281300&cid=C01504DCLVD

![Screenshot of a post in #scrapbook by thatrobotdev, with an arrow pointing at a threaded reply with a beachball emoji.](https://user-images.githubusercontent.com/18013689/85824760-c1c4a700-b73d-11ea-9d99-d61127cdd0b5.png)

**Comment by MatthewStanciu** [comment]
<img width="303" alt="Screenshot 2020-06-28 13 56 11" src="https://user-images.githubusercontent.com/14811170/85955843-2d2d9500-b947-11ea-899b-9beb0959f208.png">
bonk! 💥 Just fixed this and #14
