### ISSUE TITLE
Remove custom domain from Vercel when domain reset

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#18]
We have way more domains registered on Vercel than used in Airtable, since people sometimes set their domain multiple times. Solution is to check if someone already has a custom domain set when they run the command, and if so, make a second request to Vercel to delete the existing one https://vercel.com/docs/api#endpoints/projects/delete-a-specific-production-domain-of-a-project

**Comment by MatthewStanciu** [comment]
Yay! It works!
