### ISSUE TITLE
Idea: Comments for posts

### ISSUE THREAD

**Issue by ClaireBookworm** [hackclub/scrappy#20]
Here's an idea: Have the comments in the threads in the slack channel also show up in the scrapbook site itself as well!

-> people can toggle if they want comments for that specific post by reacting with a certain emoji
-> either the comments show up on a diff page or it's expandable underneath

This would be super cool because it'd be easier for people to see what others have said about their work without having to scroll up or check threads.

**Comment by sampoder** [comment]
another idea: have emoji reacts show up (and have them look like stickers pasted on top of the post)

**Comment by ClaireBookworm** [comment]
If we wanted to simplify that, we could model it after Instagram or Reddit and have certain emojis show up (like reddit upvote or some common emoji we use).

**Comment by MatthewStanciu** [comment]
@lachlanjc how do you feel about this? Sounds like it would largely be a task for you, maybe with a little bit of work on my end. Do you feel up for it?

**Comment by lachlanjc** [comment]
No, I don’t think we should do this. scrapbook.hackclub.com is not a social network & I don’t want it to be one—it’s more of a portfolio that we’re building over the summer of what we made, individually & collectively. The social network side of it is the #scrapbook channel in Slack, where we have comments & reactions & everything. I don’t have a comments section on each project on my website—seems weird to have a thread attached to each project of compliments & questions & whatever. (I think it’d also require a lot of work on the frontend & backend to feel good here, replicating basically every feature of Slack to make it look not broken, but the conceptual part is a lot more important.) I really appreciate everyone’s input here but I feel increasingly sure we should keep the social side on Slack & the more portfolio/profile side on the website.

**Comment by MatthewStanciu** [comment]
Cool beans. I'm going to close this for now then, but if anyone in this thread feels strongly about comments, DM me and let's talk about it! 🌟
