### ISSUE TITLE
Fix link formatting

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#23]
![2ABCC13C-80EA-47D4-A746-53F85A6EDE99](https://user-images.githubusercontent.com/5074763/85228962-d65b1500-b3b4-11ea-90c3-a6e9fa955488.jpeg)

**Comment by sampoder** [comment]
i feel like this is something to be done on the front end (unless there is a way of formatting URLs already built in)

i tried just adding a a tag in: https://scrapbook.hackclub.com/sampoder

**Comment by MatthewStanciu** [comment]
It’s a backend thing, and a similar task to formatting usernames

**Comment by MatthewStanciu** [comment]
It would be really cool if someone could make a PR to do this, otherwise I’ll get to it this week

**Comment by lachlanjc** [comment]
This uses Ruby, but basically what we want to do: https://github.com/freibuis/lita-slack/blob/master/lib/lita/adapters/slack/message_handler.rb#L54

**Comment by lachlanjc** [comment]
Handled on the frontend
