### ISSUE TITLE
Emojis aren't displaying correctly after editing a post after posting

### ISSUE THREAD

**Issue by thatrobotdev** [hackclub/scrappy#30]
I've noticed that my 😄 `:smile:` emoji is reverting back to text on my scrapbook page after editing posts.

https://scrapbook.jameskerrane.com
https://scrapbook.hackclub.com/thatrobotdev

![Screenshot of @thatrobotdev page with three posts with ":smile:" displayed. ](https://user-images.githubusercontent.com/18013689/85364247-f0dddd00-b4df-11ea-982c-2e31a4631748.jpeg)

**Comment by sampoder** [comment]
ummm... this seems to be a bigger issue

**Comment by sampoder** [comment]
![Screen Shot 2020-06-23 at 10 49 18 PM](https://user-images.githubusercontent.com/39828164/85418768-c9504880-b5a3-11ea-977d-2738034bcde7.png)

editing a post leads you to an endless beachball emoji

**Comment by MatthewStanciu** [comment]
Looks like this was fixed! Just edited a post and emojis showed up. Let me know if you run into any other issues here :)

**Comment by sampoder** [comment]
for reference it was fixed in #25
