### ISSUE TITLE
Add documentation for spinning up a local instance

### ISSUE THREAD

**Issue by jessicard** [hackclub/scrappy#311]
For future scrappy development purposes, it would be awesome to have some `README` documentation on how to spin up a local instance. Talked to @MatthewStanciu, and he mentioned a few steps:

1. Get added to “scrappy (dev)” app on slack
2. Spin up ngrok
3. Point the slack event and command urls to it

**Comment by sampoder** [comment]
We can copy this off clippy

**Comment by sampoder** [comment]
I've added something basic to the README

**Comment by jessicard** [comment]
@sampoder thank you!! this is a helpful start! when I attempt to get it running locally, I can fill the readme out a little bit more as well. let's keep this issue open as a reminder if that's cool?

**Comment by sampoder** [comment]
👍
