### ISSUE TITLE
Bug: URLs are generated from deprecated username field

### ISSUE THREAD

**Issue by jessicard** [hackclub/scrappy#312]
I created a scrapbook and saw that my scrapbook username was quite verbose (`JessicaCard-U031W2WCX3J`).

I believe this is because scrappy might be using the now-deprecated username field from the Slack API, and users added to the Hack Club Slack after the [deprecation](https://api.slack.com/changelog/2017-09-the-one-about-usernames) have their username fields automatically set to their `ID`'s for backwards compatibility.

If this is correct, I think scrappy would want to end up using `display_name` or `display_name_normalized` in the user’s `profile` object.

@MatthewStanciu mentioned, as a potential pitfall:
> ALSO I think I know why usernames are generated this way: sometimes two people would have the same or similar names so scrapbook would set their username to undefined and not actually generate a profile for them. This was probably a hacky workaround. Keep that in mind if you edit the username generation thing!

**Comment by sampoder** [comment]
If we wanted to switch away from this we could:

1. Check if `display_name` is used by another user
2. If it isn't set that with snake case or something as the username
3. Otherwise use id as a fallback

**Comment by jessicard** [comment]
@sampoder nice, I like that and that it would have a fallback. I wonder if there could also be a `/` command eventually to change your name 🤔

**Comment by exu3** [comment]
@jessicard /scrappy-setusername does that :D

<img width="454" alt="Screen Shot 2022-02-16 at 07 39 28" src="https://user-images.githubusercontent.com/72365100/154300177-42d770ca-39dc-4382-9c18-b0d00ccf8933.png">

**Comment by jessicard** [comment]
@exu3 YA'LL ARE GENIUSES omg I can fix my naaame! thank you 🙇

**Comment by jessicard** [comment]
with the set username command I don't even know if it is worth fixing this. maybe just adding a section in https://scrapbook.hackclub.com/about/ for people like me 😆

**Comment by jessicard** [comment]
Added the documentation into /about, closing this since it doesn't need to be fixed!
