### ISSUE TITLE
Idea: Message post content to slack account when it gets deleted for not including a photo

### ISSUE THREAD

**Issue by thatrobotdev** [hackclub/scrappy#33]
Whenever you post something in #scrapbook without a photo or video, scrappy will delete the post, and let you know that you need to include a video or picture.

![Video of slack, where a user types in a post and it gets deleted, with scrappy saying: "You can only share images or videos in #scrapbook!"](https://user-images.githubusercontent.com/18013689/85933611-2561e800-b896-11ea-8b0e-a4c86ff25f9d.gif)

Unfortunately, because scrappy deletes the post, you lose your writing. You cannot copy and paste it into a new message if you want to retry.

I think a better way to deal with these posts would be for scrappy to PM an account with their post content when scrappy deletes it.

**Comment by MatthewStanciu** [comment]
Totally agree, thanks for flagging ✨ Coast Guard does this in #ship, but I never brought it over to Scrappy. Will implement soon!

**Comment by MatthewStanciu** [comment]
<img width="694" alt="Screenshot 2020-06-28 11 43 26" src="https://user-images.githubusercontent.com/14811170/85953248-99eb6400-b934-11ea-8c13-b8b2cdade2f5.png">
Fixed! ⚡ @thatrobotdev let me know if you want any changes to the copy :)

**Comment by sampoder** [comment]
WooooooooOOOOHHHooooooo!!!!

**Comment by thatrobotdev** [comment]
Ahh, this is an amazing solution, thanks!

>
