### ISSUE TITLE
Add non-unfurled link to profile to CSS success reply

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#35]
Want to be able to see the CSS on someone’s page, so I know whether or not I want to apply it. Want the link to not unfurl because the thread reply + button already takes up a bunch of vertical space & the card won’t be a helpful addition there.

**Comment by MatthewStanciu** [comment]
<img width="676" alt="Screenshot 2020-06-28 12 37 19" src="https://user-images.githubusercontent.com/14811170/85954314-32391700-b93c-11ea-96b3-c74f4bb5c396.png">
💥
