### ISSUE TITLE
Add Scrapbook field to Slack profiles

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#37]
Link @username to either scrapbook.hackclub.com/username or their custom domain, as appropriate. Will make exploring peoples' scrapbooks from mobile way easier.

**Comment by MatthewStanciu** [comment]
Last I heard, Zach was against this. @zachlatta can you clarify?

**Comment by MatthewStanciu** [comment]
Just added the field. Do we also want to run a script to add people's scrapbook to their profile or should we leave it up to them to add it?

**Comment by lachlanjc** [comment]
Let’s add it to everyone if they have an account. No one will do it/defeats the point otherwise I think

**Comment by zachlatta** [comment]
I'm open with seeing how it feels. It's important that it doesn't feel non-consensual to peopl eon the Slack.
GitHub <notifications@github.com> wrote:
“Let’s add it to everyone if they have an account. No one will do it/defeats the point otherwise I think”

**Comment by MatthewStanciu** [comment]
Did we reach a conclusion on whether or not we're going to add it to everyone's profiles?

I'm against it because it's not opt-in and I don't want to frustrate people. But open to suggetions

**Comment by MatthewStanciu** [comment]
Closing this, if anyone has strong feelings either way or wants to discuss further, feel free to reopen.
