### ISSUE TITLE
Mark full-member users in Airtable

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#38]
Should happen when user record is created as well as when updated. Should also be run retroactively on all users.

**Comment by MatthewStanciu** [comment]
Done! It now checks if you're a full member every time you post to Scrapbook and marks you as a full member if you are ⚡

**Comment by lachlanjc** [comment]
Awesome. Has this been run retroactively?

**Comment by MatthewStanciu** [comment]
No, I thought you had been setting people so far? @lachlanjc 

Either way I don't think it's necessary because it checks if you're a full member every time you post in #scrapbook, so I don't think inactive members will care that they don't show up on the homepage. Thoughts?
