### ISSUE TITLE
Fallback to OG Image if no image

### ISSUE THREAD

**Issue by MatthewStanciu** [hackclub/scrappy#380]
One annoying thing about Scrappy is that you _have_ to include an image. This was great when Scrapbook first launched, but now that people are also using it for ships, I've often seen Scrappy refuse to upload their ships because they included a URL but not an image.

We've previously discussed something like opening included URL(s) and taking a screenshot, but that's hard to get right. A better fallback might be to find the open graph image for the included URL(s) and upload that as the image for the post, **iff** there is no other image attached. Just an idea!

**Comment by grymmy** [comment]
@JosiasAurel can you please coordinate with V205 in slack and have them see if this is reproducible?  assign it to them in github when they accept responsibility

**Comment by grymmy** [comment]
@JosiasAurel ping on this
