### ISSUE TITLE
scrappy 2: electric boogaloo

### ISSUE THREAD

**Issue by cfanoulis** [hackclub/scrappy#406]
this mega-issue tracks the scrappy rewrite for scrapbook v2

### Parity
 - [ ] Post to #scrapbook
 - [ ] Delete post from #scrapbook 
 - [ ] Edit post on #scrapbook
 - [ ] React to upload post
 - [ ] `/scrapbook open`
 - [ ] `/scrapbook setusername` - this should probably become a command with `username set` or `username get`
 - [ ] `/scrapbook streaks on/off/true/false/yes/no/y/n` - opt out/in streaks
 - [ ] `/scrapbook streakstatus on/off/true/false/yes/no/y/n` - opt in/out streak statuses
 - [ ] `/scrapbook css set/get` - this should probably also accept files and use their public URLs?
 - [ ] `/scrapbook audio set/get` - same as above
 - [ ] `/scrapbook webhook add/remove/list` - manage webhooks
 - [ ] `/scrapbook webring add/remove/list` - manage webrings
 - [ ] silly little replies when scrappy is mentioned

### wishlist
 - [ ] #380 
 - [ ] #197 (this would need tracking which jobs are uploading rn)
 - [ ] #110 
 - [ ] #94 (sentry?)
 - [ ] when user has a custom domain, reply with that domain instead of generic scrapbook.hackclub domain
 - [ ] keep the original @MatthewStanciu-esque transcript, maybe even he can give us even more dialogue lines?
 - [ ] `/scrapbook about` - explains what scrapbook is, redirect to the /about page
 - [ ] `/scrapbook reset` - destroys it all. burn it. with fire. AAAARSON!
 - [ ] `/scrapbook export` - zip it, yeet it.

any more requests? put them below and/or in #scrapbook-dev!
**looking for contributors!** - interested to help? dm @fanoulis on slack or join #scrapbook-dev to coordinate on making scrapper 2: the bot that will eat even more trash

**Comment by reesericci** [comment]
Can we add basic ActivityPub support to the wishlist?

**Comment by cfanoulis** [comment]
scrappy is serverless so probably not

charalampos fanoulis

student. dreamer. maker



t: https://twitter.com/cfanoulis
e: ***@***.***
