### ISSUE TITLE
Allow posting until 3 or 4am for previous day

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#41]
Should let me post after midnight to count a day's streak. Most of my scrapbook work I do at night, after work, so the midnight cutoff just breaks the experience & makes me frustrated with Scrappy.

**Comment by sampoder** [comment]
I think the rest of #scrapbook would agree with you

**Comment by MatthewStanciu** [comment]
I don't really agree with this. I think it's technically challenging and doesn't result in any clear benefit to most people—in fact, I think a later cutoff time has the potential of being confusing to people. I'm more in favor of decreasing the importance of streaks and make it not feel as bad to lose your streak.

**Comment by sampoder** [comment]
What my brother tells me about Snapchat streaks is they reset after 24hours, I'm not sure if thats right but maybe scrappy could do something similar with scrappy so like 24hrs, idk how you'd do that technically but yep

**Comment by MatthewStanciu** [comment]
Looks like it was this simple: https://github.com/hackclub/scrappy/commit/281f9c968ec46b65838eef9f45a685bf07743889

**Comment by MatthewStanciu** [comment]
I'm now subtracting 4 hours from the users' local time, so if it's anytime before 4am local time, it still counts as the previous day. ⚡

**Comment by sampoder** [comment]
wow it was lol
