### ISSUE TITLE
EDITING BROCKEN AGAIN

### ISSUE THREAD

**Issue by MatthewStanciu** [hackclub/scrappy#42]
Ok so basically editing broken

**Comment by reesericci** [comment]
Basically, if someone edits their scrapbook post in slack the changes are not reflected on the scrapbook site

**Comment by reesericci** [comment]
@MatthewStanciu where's the code for the editing? I'll take a stab at fixing it.

**Comment by sampoder** [comment]
it should be called like updated.js

**Comment by sampoder** [comment]
https://github.com/hackclub/scrappy/blob/main/pages/api/slack/message/updated.js

**Comment by MatthewStanciu** [comment]
I think the issue here is actually in api/slack/message/index.js—the updated.js api route is never called because of a condition I added there @reesericci

**Comment by reesericci** [comment]
yeah

**Comment by reesericci** [comment]
was about to say that, and then a rocket league game appeared

**Comment by reesericci** [comment]
PRS?

**Comment by reesericci** [comment]
#43

**Comment by MatthewStanciu** [comment]
Fixed in #43!
