### ISSUE TITLE
Log pronouns in Airtable

### ISSUE THREAD

**Issue by zachlatta** [hackclub/scrappy#45]
I’d like to run some stats on gender breakdown of those with streaks so we have a baseline for future improvement.

Would greatly appreciate if Scrappy could log this in the Slack Accounts table so I can do this.

**Comment by MatthewStanciu** [comment]
Pronouns are now in Airtable! Note: some pronoun fields are not filled out because the user doesn't have pronouns in Slack and they've never posted in Scrapbook. I also created a filter that filters out everyone who hasn't posted in Scrapbook before.
