### ISSUE TITLE
Logging into Scrapbook breaks the entire site

### ISSUE THREAD

**Issue by Tiger-The-Cat** [hackclub/scrappy#455]
Upon logging in via emailed token, Next.js decides to crash due to a missing "emailtoPfp" function:
![image](https://github.com/hackclub/scrappy/assets/70044734/06139486-c241-4427-ade7-c92549857971)

**Comment by JosiasAurel** [comment]
fixed in scrapbook [here](https://github.com/hackclub/scrapbook/pull/596)
