### ISSUE TITLE
% successful traffic in scrappy has no alert in grafana

### ISSUE THREAD

**Issue by grymmy** [hackclub/scrappy#461]
We should add an alert to scrappy to catch situations where % successful traffic takes a nosedive.  Example, this was observed today (10/16/23):
<img width="950" alt="Screenshot 2023-10-16 at 11 39 12 AM" src="https://github.com/hackclub/scrappy/assets/43505167/b8620228-3fc0-4f49-9d4a-88d4d2c3d7a2">

**Comment by JosiasAurel** [comment]
These alerts have been created#
<img width="1001" alt="image" src="https://github.com/hackclub/scrappy/assets/47951376/1b22ca26-407b-44cc-8ce7-6f1485cfbd42">
