### ISSUE TITLE
Merge all dependabot PRs - carefully

### ISSUE THREAD

**Issue by grymmy** [hackclub/scrappy#463]
@JosiasAurel please merge all dependabot PRs - carefully - and attempt to ensure nothing breaks as a result.

If we do not have a sanity test plan that is runnable to accommodate these scenarios where we upgrade many things, and do not have certainty that things break - perhaps we should develop one.

**Comment by grymmy** [comment]
<img width="498" alt="Screenshot 2023-10-20 at 7 43 07 PM" src="https://github.com/hackclub/scrappy/assets/43505167/899695d6-adab-4147-8af0-b1fb2c9a932f">
<img width="526" alt="Screenshot 2023-10-20 at 7 42 53 PM" src="https://github.com/hackclub/scrappy/assets/43505167/816a6954-eeb6-40a9-bab0-4b84de06eab3">

**Comment by JosiasAurel** [comment]
Each PR has been merged and tested on the scrappy staging app!
