### ISSUE TITLE
Transform user mentions to Scrapbook usernames

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#47]
When processing @mentions, instead of looking up someone’s Slack handle with the Slack API, look up their Scrapbook handle based on the user ID in Airtable instead. This will fix instances where you mention someone with a different Scrapbook username, like Christina, where the link/avatar breaks: https://scrapbook.hackclub.com/lachlanjc

**Comment by MatthewStanciu** [comment]
@lachlanjc Can you clarify a little more? I'm now looking people up on Airtable and replacing the text with their Username from Airtable, but that seems to have broken profile pics entirely 🤔 should I be replacing with another field?

**Comment by lachlanjc** [comment]
Huh, I guess I’m not totally sure then. Basically, mentioning @ christina on Slack links to a 404 on the Scrapbook site, which shouldn’t happen since she has a profile there.

**Comment by MatthewStanciu** [comment]
<img width="386" alt="Screenshot 2020-07-03 15 03 45" src="https://user-images.githubusercontent.com/14811170/86493157-6ea2b380-bd3e-11ea-9cd6-d978ffd56c36.png">
The link to Christina's profile works, but the profile pictures don't show

**Comment by MatthewStanciu** [comment]
Closing because it seems like this feature works fine. Profile pictures appear to not load anymore, but it seems like that's a frontend bug.
