### ISSUE TITLE
Investigate why scrappy cannot listen on all channels for emoji reactions

### ISSUE THREAD

**Issue by grymmy** [hackclub/scrappy#473]
Is there a reason why we need to whitelist scrappy to only respect posts in specific channels?  I could imagine there being good reasons, but also not.

**Comment by JosiasAurel** [comment]
I see two problems with this 
- someone may accidentally click the scrappy emoji and scrapbook a post that was not meant to be posted
- people might feel insecure about having a bot around in their private channels
