### ISSUE TITLE
Ignore extraneous attachments

### ISSUE THREAD

**Issue by karmanyaahm** [hackclub/scrappy#493]
If there's an image and another thing (such as a PDF) in an emoji reaction scrapbook message, scrappy should post just the text and the image, while ignoring the PDF.

**Comment by grymmy** [comment]
@karmanyaahm thanks for this - can you please do me a favor and describe the current (incorrect in your opinion) behavior, and the exact expected result?

**Comment by karmanyaahm** [comment]
Actually I'll make a PR this weekend, should be pretty easy

**Comment by karmanyaahm** [comment]
Just FYI I reproduced it here:
https://hackclub.slack.com/archives/C0536PRJWA0/p1701418217317499
https://hackclub.slack.com/archives/C0536PRJWA0/p1701418246639279

These two messages have the same attachments (one valid, one invalid), just in different order. One successfully gets scrapbooked, the other doesn't. 
I'll fix the upload validity logic and send a PR.

**Comment by karmanyaahm** [comment]
oops sorry, will get to it asap
