### ISSUE TITLE
I forgot to post yesterday, but Scrappy didn't reset my streak

### ISSUE THREAD

**Issue by zachlatta** [hackclub/scrappy#50]
Title says it all.

**Comment by sampoder** [comment]
scrappy is simply too kind to people

**Comment by MatthewStanciu** [comment]
Wow, all that work from #36 and I think this was the real issue: https://github.com/hackclub/scrappy/commit/299e20693343eca8a6cb074bf07ab78d0234f08b

@zachlatta I'm going to manually increment your streak in Airtable and then reset your streak. Let me know if you get a DM from Scrappy and your status resets

**Comment by MatthewStanciu** [comment]
Looks like it worked AND we have some code optimizations 😎 so I'm going to close this. But as always if you see this happen again, please reopen! 🙌
