### ISSUE TITLE
Order of Scrappy's Responses

### ISSUE THREAD

**Issue by sampoder** [hackclub/scrappy#56]
It would more sense for the order to be switched around here

<img width="386" alt="Screenshot 2020-07-09 at 2 02 50 PM" src="https://user-images.githubusercontent.com/39828164/87002821-009e3680-c1ed-11ea-9b5e-9abe02798822.png">

**Comment by MatthewStanciu** [comment]
Yep, this is a bug, I can't get these things to run in order. Will hopefully fix today

**Comment by sampoder** [comment]
it's probably some async thing maybe delay it by a second or so idk

**Comment by MatthewStanciu** [comment]
Fixed! ⚡
