### ISSUE TITLE
add support for uploading heic images to scrapbook

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/scrappy#574]
Might want to use the [heic-convert](https://www.npmjs.com/package/heic-convert) module

**Comment by yednapg** [comment]
@JosiasAurel could you please assign this to me?

**Comment by JosiasAurel** [comment]
just did @yednapg

**Comment by yednapg** [comment]
ty!

**Comment by grymmy** [comment]
@yednapg how's this going?

**Comment by yednapg** [comment]
Hey! I am waiting for @JosiasAurel's code walkthrough recording to get started with Scrapy!

**Comment by yednapg** [comment]
Hey! I am waiting for @JosiasAurel's code walkthrough recording to get started with Scrappy
