### ISSUE TITLE
Remove or fix skin tone from reactions

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#59]
Currently the only reaction on https://scrapbook.hackclub.com/lachlanjc is just a skin tone color, instead of a runner with the skin tone. I’m cool with entirely removing the skin tone on the backend, or otherwise we need to fix the character. It’s being parsed wrong on the Airtable end:

![4E8FE7BE-DE36-4769-9FAF-225CB334C346](https://user-images.githubusercontent.com/5074763/87216745-764ef300-c310-11ea-89a3-e50939911465.jpeg)

The site is linking to https://scrapbook.hackclub.com/r/skin-tone-5, which might be a frontend bug as well.

**Comment by MatthewStanciu** [comment]
Removed and replaced with the default yellow one! Retroactively, too. Lmk if you see any issues
