### ISSUE TITLE
API Route for turning Slack User -> Scrappy username

### ISSUE THREAD

**Issue by aramshiva** [hackclub/scrappy#597]
I would love an API route to get a slack user id and turn it into a scrappy username. It should take in a slack user id in the API url and should contain either the entire user data or just its scrappy username

**Comment by aramshiva** [comment]
I can work on this myself btw!

**Comment by JosiasAurel** [comment]
What is the entire user data here? Does that include their scrapbook updates?

**Comment by aramshiva** [comment]
Data can show the users scrappy username, slack username (confirmation?), the rest can be just found out by a second API call

**Comment by JosiasAurel** [comment]
a second api call to scrappy?

**Comment by aramshiva** [comment]
I meant, they would use this just to get the scrappy username and if they would need something like posts they can use the already built in `/api/users/[username]`. You don't need to provide that much info in this API request

**Comment by JosiasAurel** [comment]
@aramshiva what's the status on this?

**Comment by aramshiva** [comment]
I haven't been able to get this done yet. I probably wont in the near future unless I stop procrastinating.

**Comment by JosiasAurel** [comment]
I'll go ahead and close this for now. 
Note that right now we have an api for listening to scrapbook updates (which includes the poster's username). 
If you still need this particular feature please re-open.
