### ISSUE TITLE
Add command to open my profile

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#60]
/scrappy profile, perhaps?

**Comment by sampoder** [comment]
Do you mean like send a link? I don't know if slack bots can open pages in people's browsers lol

**Comment by lachlanjc** [comment]
Yup! There's just no way to get to your profile on mobile other than finding the reply to one of your posts right now.

**Comment by lachlanjc** [comment]
/scrappy-open should accept an @mention as well

**Comment by MatthewStanciu** [comment]
Done!!
