### ISSUE TITLE
Show my webring at end of all webring commands

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#61]
When I run /scrappy webring or add/remove someone, it should @mention each person in my webring at the end so I know who’s currently there.

**Comment by sampoder** [comment]
this could lead to unnecessary pings, imo it should just use their display name but not mention them

**Comment by lachlanjc** [comment]
They're in ephemeral messages, so no one mentioned will get pinged

**Comment by sampoder** [comment]
ah! makes much more sense
