### ISSUE TITLE
Improve help command copy

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#65]
![466612B2-199E-462B-9932-F5EAF664EA81](https://user-images.githubusercontent.com/5074763/87237353-60e6d100-c3c3-11ea-894d-6a83bde7ef51.jpeg)

- [ ] Capitalize command descriptions consistently
- [ ] Remove updateprofile, via #64 
- [ ] Link & capitalize Scrapbook in first sentence
- [ ] Mention that Scrappy eats trash 🗑

**Comment by sampoder** [comment]
I think my English education is adequate for me to do this
