### ISSUE TITLE
Strip or fix skin tones from emojis in post text

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#66]
![77A7BDD6-40C9-4DDE-BB44-8C5C405AA3C1](https://user-images.githubusercontent.com/5074763/87237423-17e34c80-c3c4-11ea-8be2-2ec6acf0a86b.jpeg)

**Comment by MatthewStanciu** [comment]
Done! Though not retroactively yet.

**Comment by MatthewStanciu** [comment]
Fucking FINALLY it only took 5 goddamn hours to figure out how to backpropagate but now every emoji has no skin color in airtable
