### ISSUE TITLE
Set default profile photos to googly eye animals

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/scrappy#67]

**Comment by sampoder** [comment]
I did some investigating with this. Based simply off the image URL there seems to be no recognisable pattern to see if a user is using a default profile picture. I found this URLs by clicking "Copy Image URL".

Here are two image URLs of Blue (exact same colour) Slack profile pictures. They are for different users.

https://ca.slack-edge.com/T0266FRGM-UQ46QH94Z-gc24d346e359-512

https://ca.slack-edge.com/T0266FRGM-U2Q173U05-g863c2a865d7-512

The pattern seems to be WORKSPACEID-USERID-RANDOMSTRING. Not really helpful?

Just for comparison here is Vera's profile URL: https://ca.slack-edge.com/T0266FRGM-U015B2729C3-dd1f13364d81-512

Same pattern... smh

Here are a few more random ones:

https://ca.slack-edge.com/T0266FRGM-U012KR73UAJ-g0713c52bec8-512

https://ca.slack-edge.com/T0266FRGM-U011PLSSMA9-g7e8a6705c42-512

https://ca.slack-edge.com/T0266FRGM-U015ZPLDZKQ-gf3696467c28-512

Same pattern as Vera's. 

Now one of you probably knows a solution and this piece of detective work is probably wrong. But no Google search results could tell me. 

Buttt... maybe you could use Tensorflow.js to identify default profile pictures or some image manipulation but that might be a bit overkill. 

To end, I love the idea though :)

**Comment by sampoder** [comment]
Wait except... they all start with g now I thought I had a break here but no... https://ca.slack-edge.com/T0266FRGM-UMM5KPALE-gffd01ed0a1b-512 here's an example of a profile image starting with a G that is custom :(

**Comment by MatthewStanciu** [comment]
It's not documented, but Slack's `users.info` API method has a field called `is_custom_image` referring to avatars. So we can just use that

**Comment by MatthewStanciu** [comment]
<img width="407" alt="Screenshot 2020-07-13 18 33 23" src="https://user-images.githubusercontent.com/14811170/87360170-84328d00-c537-11ea-9d4a-7d55ed8fd2e0.png">
Check it out

**Comment by sampoder** [comment]
Matthew and the undocumented slack api to my my "detective" work:

![](https://cdn.quotesgram.com/img/0/6/1995697149-sherlock-holmes-poster.png)
