### ISSUE TITLE
Scrapbook mislabeled something as failing when it didn't

### ISSUE THREAD

**Issue by sampoder** [hackclub/scrappy#80]
<img width="394" alt="Screenshot 2020-07-17 at 5 28 00 PM" src="https://user-images.githubusercontent.com/39828164/87772320-26ae8100-c854-11ea-951f-f53e8ebb4ef0.png">
<img width="296" alt="Screenshot 2020-07-17 at 5 27 56 PM" src="https://user-images.githubusercontent.com/39828164/87772328-2ada9e80-c854-11ea-8b94-64f06b6b017a.png">
<img width="700" alt="Screenshot 2020-07-17 at 5 27 52 PM" src="https://user-images.githubusercontent.com/39828164/87772366-3a59e780-c854-11ea-94ee-076a194327ec.png">

**Comment by MatthewStanciu** [comment]
I think I fixed this in https://github.com/hackclub/scrappy/commit/7fb8cc511bbed0a5780907bea85dd74ea13311c1
