### ISSUE TITLE
Scrappy got a bit excited and posted three times!

### ISSUE THREAD

**Issue by sampoder** [hackclub/scrappy#84]
<img width="1081" alt="Screenshot 2020-07-22 at 3 29 59 AM" src="https://user-images.githubusercontent.com/39828164/88098148-e17bad80-cbcb-11ea-9d62-30f5e91bc56a.png">
<img width="398" alt="Screenshot 2020-07-22 at 3 32 25 AM" src="https://user-images.githubusercontent.com/39828164/88098200-f8220480-cbcb-11ea-9d52-df5b8a3be1af.png">

**Comment by sampoder** [comment]
probs just an isolated incident

**Comment by MatthewStanciu** [comment]
This has happened before, with one of Aurora's posts. Slack does this when it doesn't receive a response from the server in time so it tries again. But this has only happened 2 or 3 times in the history of Scrapbook, and I have no idea how to fix it ¯\_(ツ)_/¯

**Comment by MatthewStanciu** [comment]
It sounds like an isolated incident in every way except for having happened multiple times

**Comment by sampoder** [comment]
I guess just manually delete in Airtable
