### ISSUE TITLE
Add stack trace logging in slack

### ISSUE THREAD

**Issue by MatthewStanciu** [hackclub/scrappy#94]
Just like Orpheus, I want to know when something went wrong. Scrappy is randomly failing for some people, to different degrees (for some people it posts but never replies, and for some people it doesn’t post). I don’t know what’s causing these failures, and I can’t reproduce them, and the logs are ephemeral so I can’t check them. So if scrappy fails to post, it should reply in the thread with the error so that I know what went wrong, and if a command fails, the command response should also reply with the error

**Comment by grymmy** [comment]
I do not support sending stack trace logs to slack.  I would rather log stack traces in a more reasonable place like an ELK stack, which we have future plans for.

If you feel this issue has been closed unnecessarily or in error, please re-open with comment - and also, please know I care deeply about issues like these and this is not an attempt to sweep things under the rug!
